config/routes.rb
LabGrader::Application.routes.draw do

 
  match '/login' => 'application#login', via: [:get, :post, :patch], :as => :login
  match '/logout' => 'application#logout', via: [:get, :post, :patch], :as => :logout
  match '*section/logout' => 'application#logout', via: [:get, :post, :patch]
  
  root :to => 'home#index'
  match '/index' => 'home#index', via: [:get, :post, :patch], :as => :home
  match '/qr' => 'home#qr', via: [:get, :post, :patch], :as => :qr
  match '/create_account' => 'home#create_account', via: [:get, :post, :patch], :as => :create_account

  match '/dashboard' => 'dashboard#index', via: [:get, :post, :patch], as: :dashboard
  match '/dashboard/import' => 'dashboard#import', via: :post, as: :import
  match '/dashboard/add_col' => 'dashboard#add_col', via: :post, as: :add_col
  match '/dashboard/remove_col' => 'dashboard#remove_col', via: :post, as: :remove_col 
  match '/dashboard/remove_student/:id' => 'dashboard#remove_student', via: [:post, :delete], as: :remove_student
  match '/dashboard/set_default_lab' => 'dashboard#set_default_lab', via: :post, as: :set_default
  match '/dashboard/mass_qr' => 'dashboard#mass_qr', via: [:get, :post], as: :mass_qr
  get 'dashboard/update' => redirect('/update')
  match '/update' => 'dashboard#index', via: [:get, :post, :patch], :as => :update
  match '/title' => 'dashboard#title', via: [:get, :post, :patch], :as => :title

  match '*section/save_grade' => 'logger#save_grade', via: [:get, :post, :patch], as: :save_grade
  match '/save_grade'=> 'logger#save_grade', via: [:get, :post, :patch]
  match '/logger' => 'logger#index', via: [:get, :post, :patch], :as => :logger 

  match '/manage' => 'account_management#index', via: [:get, :post, :patch], :as => :account_management

  match '/lostaccount' => 'lost_account#index', via: [:get, :post, :patch], :as => :lost_account

  match '/sendmail/:id' => 'emailer#sendmail', via: [:get, :post], as: :send_mail
  
  
  match '/settings' => 'settings#index', via: [:get, :post], as: :settings

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :loginCheck, :privilegeCheck, :admin, :sessionCheck
  helper_method :sort_column, :sort_direction
  
  def index

    @students = Student.order(sort_column + ' ' + sort_direction)
    @labs = Labs.first

    #allows user to create users dynamically
    if params[:FirstName].present? && params[:LastName].present?
      student = Student.create(first_name: params[:FirstName],
                               last_name: params[:LastName],
                               class_id: params[:classID],
                               email: params[:Email]
                               )
      flash[:notice] = "Student number already used." if student.errors.any?
      redirect_to :back and return


    # Used for exporting spreadsheets
    respond_to do |format|
      format.html
      format.csv { send_data @students.as_csv }
      format.xls 
    end

    #update student
    elsif params[:firstName].present? && params[:lastName].present? && params[:classId].present?
      change = Student.find(params[:id])
      change.update(first_name: params[:firstName],
                    last_name: params[:lastName],
                    class_id: params[:classId],
                    email: params[:email],
                    lab01:params[:lab01],lab02:params[:lab02],lab03:params[:lab03],lab04:params[:lab04],lab05:params[:lab05],
                    lab06:params[:lab06],lab07:params[:lab07],lab08:params[:lab08],lab09:params[:lab09],lab10:params[:lab10],
                    lab11:params[:lab11],lab12:params[:lab12],lab13:params[:lab13],lab14:params[:lab14],lab15:params[:lab15],
                    lab16:params[:lab16],lab17:params[:lab17],lab18:params[:lab18],lab19:params[:lab19],lab20:params[:lab20],
                    lab21:params[:lab21],lab22:params[:lab22],lab23:params[:lab23],lab24:params[:lab24],lab25:params[:lab25],
                    lab26:params[:lab26],lab27:params[:lab27],lab28:params[:lab28],lab29:params[:lab29],lab30:params[:lab30]
      )
      change.save
      flash[:notice] = "Successfully changed."
      redirect_to :back and return


    end

  end

  def title
    #update title

    title = Labs.first
    title.update(
        lab01_title:params[:lab01_title],lab02_title:params[:lab02_title],lab03_title:params[:lab03_title],lab04_title:params[:lab04_title],lab05_title:params[:lab05_title],
        lab06_title:params[:lab06_title],lab07_title:params[:lab07_title],lab08_title:params[:lab08_title],lab09_title:params[:lab09_title],lab10_title:params[:lab10_title],
        lab11_title:params[:lab11_title],lab12_title:params[:lab12_title],lab13_title:params[:lab13_title],lab14_title:params[:lab14_title],lab15_title:params[:lab15_title],
        lab16_title:params[:lab16_title],lab17_title:params[:lab17_title],lab18_title:params[:lab18_title],lab19_title:params[:lab19_title],lab20_title:params[:lab20_title],
        lab21_title:params[:lab21_title],lab22_title:params[:lab22_title],lab23_title:params[:lab23_title],lab24_title:params[:lab24_title],lab25_title:params[:lab25_title],
        lab26_title:params[:lab26_title],lab27_title:params[:lab27_title],lab28_title:params[:lab28_title],lab29_title:params[:lab29_title],lab30_title:params[:lab30_title]
    )
    title.save
    flash[:notice] = "Successfully changed."
    redirect_to :back and return
  end


  def mass_qr
    Student.all.each { |student| UserMailer.welcome_email(student).deliver if student.email }
    redirect_to :back, notice: "Successfully Sent Email To All Students"
  end

  def remove_student
    Student.find(params[:id]).destroy
    redirect_to :back, notice: "Successfully Removed"
  end

  # Used to import spreadsheets
  def import
    begin
      Student.import(params[:file])
      redirect_to :back, notice: "Successfully Imported"
    rescue
      redirect_to :back, notice: "File must be .csv .xls or .xlsx"
    end
  end

  # Show the next available column
  def add_col
    begin
      lab = Labs.first

      if lab.most_recent_lab > 29
        redirect_to :back, notice: "Error: Reached Maximum Number of Labs"
        return
      end

      add_max_score = params[:add_max_score].to_i
      add_max_score = 10 if add_max_score < 1

      lab.most_recent_lab += 1      
      lab_name = lab.curr_lab_to_str 
      lab.send(lab_name + "=", add_max_score) 
      lab.save

      redirect_to :back, notice: "New Lab Added With Max Score: " + add_max_score.to_s 
    rescue
      redirect_to :back, notice: "Error: Could Not Create Lab"
    end
  end

  # Remove any columnn
  def remove_col
    begin
      lab = Labs.first
      remove_lab_num = lab.most_recent_lab
      remove_lab_num = params[:remove_lab_num].to_i if params[:remove_lab_num] != ""

      if lab.most_recent_lab < 1
        redirect_to :back, notice: "Error: No Labs To Remove"
        return
      elsif remove_lab_num < 1 || remove_lab_num > lab.most_recent_lab
        redirect_to :back, notice: "Error: Lab " + remove_lab_num.to_s + " does not exist."
        return
      end
     
      # Clears any record of to be removed lab
      Student.all.each do |student|
        student.send(student.lab_to_str(remove_lab_num) + "=", nil)
        student.save
      end

      if remove_lab_num == lab.most_recent_lab 
        lab_name = lab.curr_lab_to_str
        lab.send(lab_name + "=", nil)
        lab.most_recent_lab -= 1
      else
        lab_name = lab.lab_to_str(remove_lab_num)
        lab.send(lab_name + "=", nil)
      end
     
      # Checking to see if any earlier labs are nil
      lab_name = lab.curr_lab_to_str
      until lab.most_recent_lab < 1 || lab.send(lab_name) != nil do
        lab.most_recent_lab -= 1
        lab_name = lab.curr_lab_to_str
      end
      
      lab.save
        
      redirect_to :back, notice: "Removed Lab: " + remove_lab_num.to_s
     rescue
      redirect_to :back, notice: "Error: Could Not Remove Lab"
    end
  end

  def set_default_lab
    default_num = params[:default_num].to_i
    lab = Labs.first
    lab_name = lab.lab_to_str(default_num)

    if params[:default_num] == ""
      lab.default_lab = lab.most_recent_lab
    elsif default_num > 0 && default_num <= lab.most_recent_lab && lab.send(lab_name)
      lab.default_lab = default_num
    else
      redirect_to :back, notice: "Cannot Set Lab " + params[:default_num] + " As Default Lab"
      return
    end

    lab.save
    redirect_to :back, notice: "Lab " + lab.default_lab.to_s + " Set As Default Lab"
  end

  private
  def sort_column
    Student.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end 

app/views/dashboard/index.html.erb
<h2>Dashboard</h2>
<h3>Lab Grades</h3>
<!--<p>Find me in app/views/site/index.html.erb</p>--><br>

<div id="top">
  <div id="left" style="float:left; width:80%;">
    <p>
      <em>Download:</em>
      <%= link_to "CSV", dashboard_path(format: "csv") %> |
      <%= link_to "Excel", dashboard_path(format: "xls") %>
    </p><br>
    <h5><strong>Import Students:</strong></h5>
    <%= form_tag import_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import" %>
    <% end %>
  </div>

  <div id="right" style="float:right; width:20%">  
    <h5><strong>Add New Lab:</strong></h5>
    <div>
      <%= form_tag add_col_path do %>  
        <div style="float:left;">
          <%= text_field_tag :add_max_score,
              nil,
              placeholder: "Max Score: 10",
              size: 11,
              maxlength: 3,
              class: "form-control" %>
        </div>
        <div style="float:left;">
          <%= submit_tag "Add", 
              confirm: "Are You Sure?",
              class: "btn btn-default" %>
        </div>
      <% end %> 
   </div><br><br>

    <h5><strong>Remove Lab:</strong></h5>
    <div>
      <%= form_tag remove_col_path do %>
        <div style="float:left;">
          <%= text_field_tag "remove_lab_num",
              nil,
              placeholder: "Lab: " + Labs.first.most_recent_lab.to_s,
              size: 11,
              maxlength: 2,
              class: "form-control" %>
        </div>
        <div style="float:left;">
          <%= submit_tag "Remove",
              confirm: "Remove Lab",
              class: "btn btn-default" %>
        </div>
      <% end %>
    </div><br><br>

    <h5><strong>Set Default Lab:</strong></h5>
    <div>
      <%= form_tag set_default_path do %>
        <div style="float:left;">
          <%= text_field_tag "default_num",
              nil,
              placeholder: "Default: " + Labs.first.most_recent_lab.to_s,
              size: 11,
              maxlength: 2,
              class: "form-control" %>
        </div>
        <div style="float:left;">
          <%= submit_tag "Set",
              confirm: "Set As Default Lab?",
              class: "btn btn-default" %>
        </div>
      <% end %>
    </div><br><br>


  </div>
  <div style="clear:both;"></div>
</div>

<br><font color="green"><%= notice %></font><br>

<section id="tables">
  <!--<div class="page-header">-->
  <!--<h1>Tables</h1>-->
  <!--</div>-->

  <table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
      <th>Class ID</th>
      <th><%= sortable "first_name" %></th>
      <th><%= sortable "last_name" %></th>
      <th>Email</th>
      <% (1..@labs.most_recent_lab).each do |i| %>
          <% lab_name = @labs.lab_to_str(i) %>
          <% lab_title = @labs.lab_title_to_str(i) %>
          <% if @labs.send(lab_name) %>
              <th>
                <%= "Lab " + i.to_s %>
                <%= "*" if i == @labs.default_lab %>
          	    <% title = @labs[lab_title] %>
                <% test = @labs[lab_name] %>
		        <%= "(" + test.to_s + ")" %>
                <%="\n"+ title.to_s %>
              </th>
          <% end %>
      <% end %>
      <th><a id="changeTitle" class="btn btn-default"> Title</a></th>
    </tr>
    <tr id="title" style="display: none" >
      <form action="title" method="get">
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <% (1..@labs.most_recent_lab).each do |i| %>
            <% lab_name = @labs.lab_to_str(i) %>
            <% lab_title = @labs.lab_title_to_str(i) %>
            <% if @labs.send(lab_name) %>
                <th>
                  <% title = @labs[lab_title] %>
                  <input id="title" type="text" name="<%=lab_title %>" class="form-control" placeholder="Enter title" value="<%=title.to_s%>"/>

                </th>
            <% end %>
        <% end %>


        <td><input id="cancel" class="btn btn-default" type="button" value="Cancel"/></td>
        <td><input id="change" class="btn btn-default" type="submit" value="Change"/></td>
      </form>
    </tr>
    </thead>
    <tbody>


    <% for student in @students do %>
        <tr id="list<%=student.id%>">
          <td><%= student.class_id %></td>
          <td><%= student.first_name %></td>
          <td><%= student.last_name %></td>
          <td><%= link_to student.email, send_mail_path(student), confirm: "Are You Sure?" %></td>
          <% (1..@labs.most_recent_lab).each do |i| %>
              <% lab_name = @labs.lab_to_str(i) %>
              <% student_lab = student.lab_to_str(i) %>

              <td><%= student.send(student_lab) if @labs.send(lab_name) %></td>
          <% end %>
          <td>
            <a id="edit<%=student.id%>" class="btn btn-default"> Edit</a>
          </td>
          <td>
            <%= button_to "Remove",
                          remove_student_path(student),
                          confirm: "Are You Sure?",
                          class: "btn btn-default" %>
          </td>
        </tr>
        <tr id="form<%=student.id %>" style="display: none " >
          <form action="update" method="get">
            <input style="display: none;" type="text" name="id" value="<%=student.id%>"/>
            <td><input type="text" class="form-control" id="classId" name="classId" placeholder="Enter class ID" value="<%= student.class_id %>"/></td>
            <td><input type="text" class="form-control" id="firstname" name="firstName" placeholder="Enter first name" value="<%= student.first_name %>"/></td>
            <td><input type="text" class="form-control" id="lastname" name="lastName" placeholder="Enter last name" value="<%= student.last_name %>"/></td>
            <td><input type="text" class="form-control" id="email" name="email" placeholder="Enter email" value="<%= student.email%>"/></td>
            <% (1..@labs.most_recent_lab).each do |i| %>
                <% lab_name = @labs.lab_to_str(i) %>
                <% student_lab = student.lab_to_str(i) %>
                <td><input type="text"  class="form-control col-sm-1" id="<%= lab_name[0..4] %>" name="<%=lab_name[0..4]%>" value="<%= student.send(student_lab) if @labs.send(lab_name) %>"/></td>
            <% end %>

            <td><input id="cancel<%=student.id%>" class="btn btn-default" type="button" value="Cancel"/></td>
            <td><input id="change<%=student.id%>" class="btn btn-default" type="submit" value="Change"/></td>
          </form>
        </tr>
        <script>
            $(document).ready(function(){
                $('#changeTitle').click(function(){
                    $('#title').css('display','' );
                    $('#changeTitle').css('display','none' );
                });
                $('#cancel').click(function(){
                    $('#title').css('display','none');
                    $('#changeTitle').css('display','' );
                });
                var div = document.getElementById('container')
                    $('#container').append("<"+ "script" +">"
                            + "$('#"+"edit"+"<%=student.id%>"+"')" +".click(function(){"
                            + "$('#"+"form"+"<%=student.id%>"+"')"+ ".css('display', '');"
                            + "$('#"+"list"+"<%=student.id%>"+"')"+ ".css('display', 'none');"
                            +"});"

                            + "$('#"+"cancel"+"<%=student.id%>"+"')" +".click(function(){"
                            + "$('#"+"form"+"<%=student.id%>"+"')"+ ".css('display', 'none');"
                            + "$('#"+"list"+"<%=student.id%>"+"')"+ ".css('display', '');"
                            +"});"

                            + "</" +"script" +">");

            });


        </script>
    <% end %>

    </tbody>
  </table>
</section>


<!--form allowing users to enter first and last name of a person to be added to the table -->
<h4>Add Additional Student</h4>
<div class="input-group">
  <form name="input" action="dashboard" method="get">
    <div class="row">
      <div class="col-lg-2">
            <span class="input-group-btn">
              <input style="width:auto;" type="text" name="FirstName" class="form-control" placeholder="First Name" required="true">
              <input style="width:auto;" type="text" name="LastName" class="form-control" placeholder="Last Name" required="true">
              <input style="width:auto;" type="text" name="classID" class="form-control" placeholder="Class ID" required="true">
              <input style="width:auto;" type="text" name="Email" class="form-control" placeholder="Email" required="true">
              <button style="width:auto;" type="submit" value="Submit" class="btn btn-default">Add</button>
            </span>
      </div>
    </div>
  </form>
</div>

<h4>Find QR Code</h4>
<div class="input-group">
  <form name="input" action="qr" method="get">
    <div class="row">
      <div class="col-lg-2">
            <span class="input-group-btn">
                <input style="width:auto;" type="text" name="Class_id" class="form-control" placeholder="Class ID" required="true">
                <button  style="width:auto;" type="submit" value="Submit" class="btn btn-default">Find</button>
            </span>
      </div>
    </div>
  </form>
</div>

<h4>Send Email To All Students</h4>
<%= button_to "Send", mass_qr_path, confirm: "Are You Sure?", class: "btn btn-default" %>

app/views/dashboard/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">first_name</Data></Cell>
        <Cell><Data ss:Type="String">last_name</Data></Cell>
        <Cell><Data ss:Type="String">class_id</Data></Cell>
	<% if Labs.first.most_recent_lab > 0 %>
	  <% (1..Labs.first.most_recent_lab).each do |i| %>
	    <% lab_name = Labs.first.lab_to_str(i) %>
            <Cell><Data ss:Type="String"><%= Student.first.lab_to_str(i) if Labs.first.send(lab_name) %></Data></Cell>
	  <% end %>
        <% end %>
        <Cell><Data ss:Type="String">email</Data></Cell> 
      </Row>
     
      <% @students.each do |student| %>
        <Row>
          <Cell><Data ss:Type="String"><%= student.first_name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= student.last_name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= student.class_id %></Data></Cell>
  	  <% if Labs.first.most_recent_lab > 0 %>
	    <% (1..Labs.first.most_recent_lab).each do |i| %>
	      <% lab_name = student.lab_to_str(i) %>
              <Cell><Data ss:Type="Number"><%= student.send(lab_name) if student.send(lab_name) %></Data></Cell>
	    <% end %>
	  <% end %>
          <Cell><Data ss:Type="String"><%= student.email %></Data></Cell>
        </Row>
      <% end %>
    
    </Table>
  </Worksheet>
</Workbook>