config/routes.rb
LabGrader::Application.routes.draw do

 
  match '/login' => 'application#login', via: [:get, :post, :patch], :as => :login
  match '/logout' => 'application#logout', via: [:get, :post, :patch], :as => :logout
  match '*section/logout' => 'application#logout', via: [:get, :post, :patch]
  
  root :to => 'home#index'
  match '/index' => 'home#index', via: [:get, :post, :patch], :as => :home
  match '/qr' => 'home#qr', via: [:get, :post, :patch], :as => :qr
  match '/create_account' => 'home#create_account', via: [:get, :post, :patch], :as => :create_account

  match '/dashboard' => 'dashboard#index', via: [:get, :post, :patch], as: :dashboard
  match '/dashboard/import' => 'dashboard#import', via: :post, as: :import
  match '/dashboard/add_col' => 'dashboard#add_col', via: :post, as: :add_col
  match '/dashboard/remove_col' => 'dashboard#remove_col', via: :post, as: :remove_col 
  match '/dashboard/remove_student/:id' => 'dashboard#remove_student', via: [:post, :delete], as: :remove_student
  match '/dashboard/set_default_lab' => 'dashboard#set_default_lab', via: :post, as: :set_default
  match '/dashboard/mass_qr' => 'dashboard#mass_qr', via: [:get, :post], as: :mass_qr
  get 'dashboard/update' => redirect('/update')
  match '/update' => 'dashboard#index', via: [:get, :post, :patch], :as => :update
  match '/title' => 'dashboard#title', via: [:get, :post, :patch], :as => :title

  match '*section/save_grade' => 'logger#save_grade', via: [:get, :post, :patch], as: :save_grade
  match '/save_grade'=> 'logger#save_grade', via: [:get, :post, :patch]
  match '/logger' => 'logger#index', via: [:get, :post, :patch], :as => :logger 

  match '/manage' => 'account_management#index', via: [:get, :post, :patch], :as => :account_management

  match '/lostaccount' => 'lost_account#index', via: [:get, :post, :patch], :as => :lost_account

  match '/sendmail/:id' => 'emailer#sendmail', via: [:get, :post], as: :send_mail
  
  
  match '/settings' => 'settings#index', via: [:get, :post], as: :settings

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :admin, :sessionCheck

  def index
    @account = Account.all

    #prints qr code to page
    if session[:username] != nil
      if Account.find_by_username(session[:username]) != nil
      @student = Student.find_by_class_id(Account.find_by_username(session[:username]).class_id)
      end
      if @student != nil
        #keep qr code tied to class id so no sensitive information can be taken from code
        @qr = RQRCode::QRCode.new(url_for(controller: 'logger') +'?Class_id='+
                                  @student.class_id.to_s,
                                  size: 4,
                                  level: :l)
        @png = @qr.to_img.resize(250,250)
        @labs2 = Labs.first
      end
    end

    if params[:account].present? && params[:password].present? && params[:password2].present?
      #deal with all the error messsages for incorrect form fills
      errors = Array.new
      if Student.find_by_class_id(params[:class_id].to_i) == nil
        errors.push "Not a recognized student number."
      end
      if Account.find_by_class_id(params[:class_id].to_i) != nil
        errors.push "Student number already used."
      end
      if Account.find_by_username(params[:account].downcase) != nil
        errors.push "Username is already used."
      end
      if params[:password].length < 6
        errors.push "Passwords is too short, 1-6 characters."
      end
      if params[:password] != params[:password2]
        errors.push "Passwords do not match."
      end
      
      if !errors.empty?
        flash[:notice] = errors.join("<br>").html_safe
      else
        #creates account if form is completed properly
          accounts = Account.create(username: params[:account].downcase,
                                 password: BCrypt::Password.create(params[:password]),
                                 privilege: 0,
                                 reset: 0,
                                 class_id: params[:class_id].to_i)

        errors = "<font color='green'> Account successfully created. </font>"
        flash[:notice] = errors.html_safe
      end
      redirect_to home_path
    end
  end

  def about
  end

  def qr
    #currently using nshe, maybe change to more intuitive name later
    @student = Student.find_by_class_id(params[:Class_id])
    if @student != nil
      #keep qr code tied to class id so no sensitive information can be taken from code
      @qr = RQRCode::QRCode.new(url_for(controller: 'logger') +'?Class_id='+ 
                                  @student.class_id.to_s,
                                  size: 4,
                                  level: :l)
      @png = @qr.to_img.resize(250,250)
    else
      if params[:Class_id].present?
        flash[:notice] = "Student " + params[:Class_id] + " does not exist"
      else
        flash[:notice] = "You did not enter a student id."
      end
      redirect_to :back
    end
  rescue
    redirect_to root_path
  end
end

app/views/home/index.html.erb
<h2>LabGrader</h2>
<body>
    <h4>Welcome to our Lab Grade Logging System!</h4>
   
<% if session[:username] == nil %>
    <h5>If you do not have an account create one below.</h5>
<% else %>

     <% if Account.find_by_username(session[:username]).privilege == 1 %>
        <h5>Click the tabs above to navigate the pages.</h5>
     <%else%>
        <h5>You can find your qr code, and lab scores below. For your convienence you may want to save the qr code image by right clicking it.</h5>
     <%end%>

<% end %>
</body>



<!--<p>Find me in app/views/site/index.html.erb</p>-->
<font color="red"> <%= flash[:notice] %></font>
<br>

<% if session[:username] != nil %>
    <% if @png != nil %>
        <img width="250" height="250" src="<%= @png.to_data_url %>" />
   <% end %>

    <br>

      <% if @student != nil %>
          <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
              <% (1..@labs2.most_recent_lab).each do |i| %>
                  <% lab_name = @labs2.lab_to_str(i) %>
                  <th><%= "Lab " + i.to_s  if @labs2.send(lab_name) %></th>
              <% end %>
            </tr>
            </thead>
            <tbody>
            <tr>
              <% (1..@labs2.most_recent_lab).each do |i| %>
                  <% lab_name = @labs2.lab_to_str(i) %>
                  <% student_lab = @student.lab_to_str(i) %>
                  <td><%= @student.send(student_lab) if @labs2.send(lab_name) %></td>
              <% end %>
            </tr>
            </tbody>
          </table>
      <%end%>

<%end%>

<% if session[:username] == nil %>
 
   <h4>Create User Account</h4>
    <div class="input-group">
      <form name="input" action="index" method="get">
        <div class="row">
          <div class="col-lg-2">
            <span class="input-group-btn">
              <input style="width:auto;" type="text" name="account" class="form-control" placeholder="Username" required="true">
              <br>
              <input style="width:auto;" type="password" name="password" class="form-control" placeholder="Password" required="true">
              <br>
              <input style="width:auto;" type="password" name="password2" class="form-control" placeholder="Confirm password" required="true">
              <br>
              <input style="width:auto;" type="text" name="class_id" class="form-control" placeholder="Class ID" required="true">
              <br>
              <button style="width:auto;" type="submit" value="Submit" class="btn btn-default">Create</button>
            </span>
          </div>
        </div>
      </form>
    </div>

    <br>

<%= link_to "Forgot your password?", lost_account_path, method: :get %>

    <br>


<h5>If you don't want to make an account you can find your qr code below.</h5>
    <div class="input-group">
      <form name="input" action="qr" method="get">
        <div class="row">
          <div class="col-lg-2">
            <span class="input-group-btn">
              <input style="width:auto;" type="text" name="Class_id" class="form-control" placeholder="Class ID" required="true">
              <button  style="width:auto;" type="submit" value="Submit" class="btn btn-default">Find</button>
            </span>
          </div>
        </div>
      </form>
    </div>
<% end %>

app/views/home/qr.erb
<img width="250" height="250" src="<%= @png.to_data_url %>" />