config/routes.rb
LabGrader::Application.routes.draw do

 
  match '/login' => 'application#login', via: [:get, :post, :patch], :as => :login
  match '/logout' => 'application#logout', via: [:get, :post, :patch], :as => :logout
  match '*section/logout' => 'application#logout', via: [:get, :post, :patch]
  
  root :to => 'home#index'
  match '/index' => 'home#index', via: [:get, :post, :patch], :as => :home
  match '/qr' => 'home#qr', via: [:get, :post, :patch], :as => :qr
  match '/create_account' => 'home#create_account', via: [:get, :post, :patch], :as => :create_account

  match '/dashboard' => 'dashboard#index', via: [:get, :post, :patch], as: :dashboard
  match '/dashboard/import' => 'dashboard#import', via: :post, as: :import
  match '/dashboard/add_col' => 'dashboard#add_col', via: :post, as: :add_col
  match '/dashboard/remove_col' => 'dashboard#remove_col', via: :post, as: :remove_col 
  match '/dashboard/remove_student/:id' => 'dashboard#remove_student', via: [:post, :delete], as: :remove_student
  match '/dashboard/set_default_lab' => 'dashboard#set_default_lab', via: :post, as: :set_default
  match '/dashboard/mass_qr' => 'dashboard#mass_qr', via: [:get, :post], as: :mass_qr
  get 'dashboard/update' => redirect('/update')
  match '/update' => 'dashboard#index', via: [:get, :post, :patch], :as => :update
  match '/title' => 'dashboard#title', via: [:get, :post, :patch], :as => :title

  match '*section/save_grade' => 'logger#save_grade', via: [:get, :post, :patch], as: :save_grade
  match '/save_grade'=> 'logger#save_grade', via: [:get, :post, :patch]
  match '/logger' => 'logger#index', via: [:get, :post, :patch], :as => :logger 

  match '/manage' => 'account_management#index', via: [:get, :post, :patch], :as => :account_management

  match '/lostaccount' => 'lost_account#index', via: [:get, :post, :patch], :as => :lost_account

  match '/sendmail/:id' => 'emailer#sendmail', via: [:get, :post], as: :send_mail
  
  
  match '/settings' => 'settings#index', via: [:get, :post], as: :settings

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LabGrader</title>
  <!--<link rel="shortcut icon" href="../images/favicon.ico" type="image/x-icon">-->
  <!--<link rel="icon" href="../images/favicon.ico" type="image/x-icon">-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

        <li style="float:left;"><a class="navbar-brand" href=<%=root_path%>><h5>LabGrader</h5></a></li>
        <% if session[:username] && Account.find_by_username(session[:username]) && Account.find_by_username(session[:username]).privilege == 1 %>
          <li style="float:left;"><a href=<%=dashboard_path%>><h5>Dashboard</h5></a></li>
          <li style="float:left;"><a href=<%=logger_path%>><h5>Logger</h5></a></li>
          <li style="float:left;"><a href=<%=account_management_path%>><h5>Accounts</h5></a> </li>
          <li style="float:left;"><a href=<%=settings_path%>><h5>Settings</h5></a> </li>
       <% end %>

       <% if session[:username] != nil %>
            <li style="margin-top:4mm;float:left;width:20%">
               <form name="input" action="logout" method="get">
                   <span class="input-group-btn">
                     <button  type="submit" value="Submit" class="btn btn-default">Logout</button>
                    <%=link_to session[:username], account_management_path, method: :get%> 
                   </span>
                </form>
            </li>
        <%end%>

        <% if session[:username] == nil %>
   
           <form name="input" action="login" method="get">
	     <li style="margin-top:4mm;float:left"><a><button type="submit" value="Submit" class="btn btn-default">Login</button></a></li>
             <li style="margin-top:4mm;width:20%;float:left"><a><input type="text" name="username" class="form-control" placeholder="username" required="true"></a></li>
             <li style="margin-top:4mm;width:20%;float:left"><a><input type="password" name="password" class="form-control" placeholder="password" required="true"></a></li>
           </form>
                
        <%end%>
      </ul>
    </div>
  </div>
</nav>
</div>

<div id="container" class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    <% act = Account.find_by_username('admin') %>
    <% if !act.nil? && !act.setting.nil? %>
      <%= act.setting.org %>
    <% end %>
  </div>
</footer>
</body>
</html>